### ISSUE TITLE
Turn off all lights on application exit

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/sparkles#13]
When the application shuts down, we should turn all the lights off by switch the relays to the off position.

**Comment by khalidabuhakmeh** [comment]
@williambogaiv this seems to be the case now, is this issue resolved?

**Comment by billbogaiv** [comment]
No. Still need to add this. The lights shut-off when the raspi reboots.

**Comment by jrusbatch** [comment]
Since we don't have sparkles set up right now, is this still relevant?

**Comment by billbogaiv** [comment]
No. This was more of a feature request (than a bug) and did not turn into a problem during our usage.
