### ISSUE TITLE
Design Logo for Sparkles

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/sparkles#19]
Design a logo that will be used in the readme and the dashboard.

**Comment by khalidabuhakmeh** [comment]
![sparkles_logo](https://cloud.githubusercontent.com/assets/228256/4985679/fad06ea6-692f-11e4-9986-4d4139434d69.png)

**Comment by khalidabuhakmeh** [comment]
![logo_2](https://cloud.githubusercontent.com/assets/228256/4985735/b9dcf56c-6930-11e4-8c8c-073f73e67fe7.png)

**Comment by jrusbatch** [comment]
Lose the text. The icon by itself would be perfect.

**Comment by khalidabuhakmeh** [comment]
Lose the text?

**Comment by khalidabuhakmeh** [comment]
![](http://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Emoji_u2728.svg/2000px-Emoji_u2728.svg.png)

**Comment by jrusbatch** [comment]
@khalidabuhakmeh I like it.

**Comment by ScottSchwalm** [comment]
I kinda like the second one.

**Comment by scottkowalski** [comment]
Who came up with ‘Sparkles’?  I think we need a vote on the name.

**Comment by khalidabuhakmeh** [comment]
![sparkles_colon](https://cloud.githubusercontent.com/assets/228256/4993323/f62aaa60-697a-11e4-8ec1-1adf9324990f.png)

**Comment by khalidabuhakmeh** [comment]
@scottkowalski 
![rsparkles](https://cloud.githubusercontent.com/assets/228256/4993359/5ad4c27a-697b-11e4-9037-30f7a0a9d766.png)

**Comment by scottkowalski** [comment]
Nice… ARRRGGGHHHHH sparkles

**Comment by billbogaiv** [comment]
@khalidabuhakmeh Going with [this one](https://github.com/ritterim/sparkles/issues/19#issuecomment-62544945) for now. See #20.

**Comment by khalidabuhakmeh** [comment]
![_sparkles_](https://cloud.githubusercontent.com/assets/228256/4996373/2622cbf2-6995-11e4-896b-0482f91bc890.jpg)

used in the UI here :)

**Comment by billbogaiv** [comment]
For ref., here is the source of the sparkles logo: http://commons.wikimedia.org/wiki/File:Emoji_u2728.svg
